In [3]:
import numpy as np

In [4]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
mean_a = [a[:, i].mean() for i in range(2)]

In [7]:
mean_a

[2.0, 8.4]

In [8]:
a_centered = a - mean_a

In [9]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [10]:
a_centered_sp = a_centered[:, 0].dot(a_centered[:, 1])

In [11]:
a_centered_sp

8.0

In [12]:
a_centered_sp / (a.shape[0] - 1)

2.0

In [13]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])